=== convidev-tud/consistency-benchmark/meta/XSL/operations.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://mergebench.org/ns"
           xmlns="http://mergebench.org/ns"
           xmlns:mergebench="http://mergebench.org/ns"
           elementFormDefault="qualified">

    <xs:element name="Evolution">
        <xs:complexType>
            <xs:sequence>

            <!-- a group of syntactical changes serving a combined purpose -->
            <xs:element name="SemanticEdit" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>

                        <!-- give the change a semantic for better interpretability in future studies -->
                        <xs:element name="Semantic" minOccurs="1" maxOccurs="1">
                            <xs:complexType>
                                <xs:sequence>
                                    <!-- semantic category/label for better change classification -->
                                    <xs:element name="Category" minOccurs="1" maxOccurs="unbounded">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="ADAPT"/> <!-- general miscellaneous change, possibly due to requirement changes -->
                                                <xs:enumeration value="REFINE"/> <!-- add more detailles (depth) -->
                                                <xs:enumeration value="EXTEND"/> <!-- add more elements (width) -->
                                                <xs:enumeration value="SIMPLYFY"/> <!-- remove detailles to make the model more abstract (depth) -->
                                                <xs:enumeration value="REDUCE" /> <!-- remove elements to make the model smaller (width) -->
                                                <xs:enumeration value="REPURPOSE"/> <!-- keep the syntactical structure but transfer the domain --> 
                                                <xs:enumeration value="REFACTOR RESTRUCTURE"/> <!-- keep semantics put change the way its modeled (subtle, structure) -->
                                                <xs:enumeration value="REFACTOR RENAME"/> <!-- keep semantics put change the way its modeled (subtle, namings) -->
                                                <!-- To Discuss -->
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>

                                    <!-- human written description of the change -->
                                    <xs:element name="Description" type="xs:string" minOccurs="0" maxOccurs="1" />
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>

                        <xs:element name="Operation" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:choice>
                                
                                    <!-- DELETIONS -->

                                    <!-- delete a node, the all of the node's properties must be deleted beforehand -->
                                    <xs:element name="DeleteNode">
                                        <xs:complexType>
                                            <xs:attribute name="nodeName" type="xs:anyURI" use="required"/>
                                            <xs:attribute name="groupName" type="xs:anyURI" use="required"/>
                                        </xs:complexType>
                                    </xs:element>

                                    <!-- delete a directed edge (revertible) -->
                                    <xs:element name="DeleteDirectedEdge">
                                        <xs:complexType>
                                            <xs:attribute name="start" type="xs:anyURI" use="required"/>
                                            <xs:attribute name="end" type="xs:anyURI" use="required"/>
                                            <xs:attribute name="semantics" type="xs:anyURI" use="required"/>
                                        </xs:complexType>
                                    </xs:element>

                                    <!-- delete a group, all elements within the group must be removed or moved in edits with smaller indices (revertible) -->
                                    <xs:element name="DeleteGroup">
                                        <xs:complexType>
                                            <xs:attribute name="groupName" type="xs:anyURI" use="required"/>
                                        </xs:complexType>
                                    </xs:element>

                                    <!-- remove paroperty from a specified node. This is not ambigious as both node and properties are unique-->
                                    <xs:element name="DeleteProperty">
                                        <xs:complexType>
                                            <xs:attribute name="nodeName" type="xs:anyURI" use="required"/>
                                            <xs:attribute name="propertyName" type="xs:anyURI" use="required"/>
                                        </xs:complexType>
                                    </xs:element>


                                    <!-- Additions -->

                                    <!-- add a new node to an existing group -->
                                    <xs:element name="AddNode">
                                        <xs:complexType>
                                            <xs:attribute name="nodeName" type="xs:anyURI" use="required"/>
                                            <xs:attribute name="groupName" type="xs:anyURI" use="required"/>
                                        </xs:complexType>
                                    </xs:element>

                                    <!-- add a new directed edge. connected nodes must already exist -->
                                    <xs:element name="AddDirectedEdge">
                                        <xs:complexType>
                                            <xs:attribute name="start" type="xs:anyURI" use="required"/>
                                            <xs:attribute name="end" type="xs:anyURI" use="required"/>
                                            <xs:attribute name="semantics" type="xs:anyURI" use="required"/>
                                        </xs:complexType>
                                    </xs:element>

                                    <!-- add a new group -->
                                    <xs:element name="AddGroup">
                                        <xs:complexType>
                                            <xs:attribute name="groupName" type="xs:anyURI" use="required"/>
                                        </xs:complexType>
                                    </xs:element>

                                    <!-- Modifications / Renamings -->

                                    <!-- rename a property, this should not be used to repurpose a property but only in the context of refactoring or domain transfer -->
                                    <xs:element name="RenameProperty">
                                        <xs:complexType>
                                            <xs:attribute name="nodeName" type="xs:anyURI" use="required"/>
                                            <xs:attribute name="oldPropertyName" type="xs:anyURI" use="required"/>
                                            <xs:attribute name="newPropertyName" type="xs:anyURI" use="required"/>
                                        </xs:complexType>
                                    </xs:element>

                                    <!--Add Property-->
                                    <xs:element name="AddProperty">
                                        <xs:complexType>
                                            <xs:attribute name="nodeName" type="xs:anyURI" use="required"/>
                                            <xs:attribute name="propertyName" type="xs:anyURI" use="required"/>
                                        </xs:complexType>
                                    </xs:element>

                                    <!-- rename a group, this should not be used to repurpose a group but only in the context of refactoring or domain transfer -->
                                    <xs:element name="RenameGroup">
                                        <xs:complexType>
                                            <xs:attribute name="oldGroupName" type="xs:anyURI" use="required"/>
                                            <xs:attribute name="newGroupName" type="xs:anyURI" use="required"/>
                                        </xs:complexType>
                                    </xs:element>

                                    <!-- rename a node, this should not be used to repurpose a node but only in the context of refactoring or domain transfer -->
                                    <xs:element name="RenameNode">
                                        <xs:complexType>
                                            <xs:attribute name="oldNodeName" type="xs:anyURI" use="required"/>
                                            <xs:attribute name="newNodeName" type="xs:anyURI" use="required"/>
                                        </xs:complexType>
                                    </xs:element>

                                    <!-- change the semanitcs label of a directed edge, this should not be used for repurposing but for refining, abstracting or domain transfer -->
                                    <xs:element name="ChangeSemanticsDirectedEdge">
                                        <xs:complexType>
                                            <xs:attribute name="start" type="xs:anyURI" use="required"/>
                                            <xs:attribute name="end" type="xs:anyURI" use="required"/>
                                            <xs:attribute name="oldSemantics" type="xs:anyURI" use="required"/>
                                            <xs:attribute name="newSemantics" type="xs:anyURI" use="required"/>
                                        </xs:complexType>
                                    </xs:element>

                                    <!-- Modifications / Complex Actions -->

                                    <!-- move a node from one group to another, both groups must exist -->
                                    <xs:element name="MoveNodeToOtherGroup">
                                        <xs:complexType>
                                            <xs:attribute name="nodeName" type="xs:anyURI" use="required"/>
                                            <xs:attribute name="oldGroupName" type="xs:anyURI" use="required"/>
                                            <xs:attribute name="newGroupName" type="xs:anyURI" use="required"/>
                                        </xs:complexType>
                                    </xs:element>

                                    <!-- join/merge two groups under a new name, this combines the two sets of nodes into a new set -->
                                    <xs:element name="JoinGroups">
                                        <xs:complexType>
                                            <xs:attribute name="group1Name" type="xs:anyURI" use="required"/>
                                            <xs:attribute name="group2Name" type="xs:anyURI" use="required"/>
                                            <xs:attribute name="newGroupName" type="xs:anyURI" use="required"/>
                                        </xs:complexType>
                                    </xs:element>
                                
                                </xs:choice>

                                <xs:attribute name="index" type="xs:int" use="required"/>
                            </xs:complexType>
                        </xs:element>

                    </xs:sequence>

                    <xs:attribute name="index" type="xs:int" use="required"/>

                </xs:complexType>
            </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== convidev-tud/consistency-benchmark/data/EXAMPLE/evolution_a.xml
<?xml version="1.0"?>
<Evolution xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://mergebench.org/ns"
          xsi:schemaLocation="http://mergebench.org/ns ../../meta/XSL/operations.xsd">

    <SemanticEdit index="0">
        <Semantic>
            <Category>REPURPOSE</Category>
            <Description>
                Change the names of the pets.
                The model is migrated for a new customer with different pets.
            </Description>
        </Semantic>
        <Operation index="0">
            <RenameNode oldNodeName="dog" newNodeName="mouse" />
        </Operation>
        <Operation index="1">
            <RenameNode oldNodeName="cat" newNodeName="hamster" />
        </Operation>
    </SemanticEdit>

    <SemanticEdit index="1">
        <Semantic>
            <Category>SIMPLYFY</Category>
            <Description>
                Remove the age property from the pets.
                The new customer does not need to know the age of the pets.
            </Description>
        </Semantic>
        <Operation index="0">
            <DeleteProperty nodeName="mouse" propertyName="age" />
        </Operation>
        <Operation index="1">
            <DeleteProperty nodeName="hamster" propertyName="age" />
        </Operation>
    </SemanticEdit>

</Evolution>
